name: wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  flustars_flutter3: ^3.0.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  flutter_svg: ^1.1.1+1
  permission_handler: ^9.2.0
  logger: ^1.0.0
  path_provider: ^2.0.2
  fast_gbk: ^1.0.0
  event_bus: ^2.0.0
  device_info_plus: ^3.2.2
  package_info_plus: ^1.4.0
  uni_links: ^0.5.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_smart_dialog: ^4.3.1
  connectivity_plus: ^2.2.1
  pull_to_refresh:
    git: 
      url: https://github.com/fplugins/flutter_pulltorefresh.git

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  json_model: ^1.0.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  build_runner: any
  retrofit_generator: ^4.0.2

flutter: 
  uses-material-design: true

assets:
  # assets-generator-begin
  # assets-generator-end